add github step summaries

diff --git a/.github/workflows/docker-cd.yaml b/.github/workflows/docker-cd.yaml
--- a/.github/workflows/docker-cd.yaml
+++ b/.github/workflows/docker-cd.yaml
@@ -167,7 +167,7 @@ jobs:
             .dockerconfigjson: |
               {
                 "auths": {
-                  "ghcr.io": {
+                  "${{ env.REGISTRY }}": {
                     "username": "${{ secrets.GHCR_USER }}",
                     "password": "${{ secrets.GHCR_TOKEN }}"
                   }
@@ -177,7 +177,13 @@ jobs:
 
       - name: Apply secret to Kubernetes
         run: |
-          kubectl apply -f secrets.yaml
+          kubectl apply -f secrets.yaml || true
+          sleep 10
+          if kubectl get secret -n ${{ github.ref_name }} | grep -q ghcr-auth; then
+            echo "secrets.yaml applied successfully" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "Secrets.yaml failed to apply" >> $GITHUB_STEP_SUMMARY
+          fi
 
   Create-Deployment:
     needs: Create-Secret
@@ -320,7 +326,13 @@ jobs:
 
       - name: Apply Deployment file
         run: |
-          kubectl apply -f deployment.yaml
+          kubectl apply -f deployment.yaml || true
+          sleep 10
+          if kubectl get deployment -n ${{ github.ref_name }} | grep -q ${{ env.IMAGE_NAME }}; then
+            echo "deployment.yaml applied successfully" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "deployment.yaml failed to apply" >> $GITHUB_STEP_SUMMARY
+          fi
 
   Create-Service:
     needs: Create-Deployment
@@ -379,7 +391,13 @@ jobs:
 
       - name: Apply Service file
         run: |
-          kubectl apply -f service.yaml
+          kubectl apply -f service.yaml || true
+          sleep 10
+          if kubectl get service -n ${{ github.ref_name }} | grep -q ${{ env.IMAGE_NAME }}; then
+            echo "service.yaml applied successfully" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "service.yaml failed to apply" >> $GITHUB_STEP_SUMMARY
+          fi
 
   Create-Route53:
     needs: Create-Service
@@ -429,6 +447,22 @@ jobs:
             }]
           }'
 
+          # Check if CNAME record was created successfully
+          sleep 10
+          if [ "$(aws route53 list-resource-record-sets --hosted-zone-id $ZONE_ID --query "ResourceRecordSets[?Type == 'CNAME' && Name == 'ce7-grp-2-app-'${{ github.ref_name }}'.sctp-sandbox.com.'].ResourceRecords[*].Value" --output text)" = "$EXTERNAL_IP" ]; then
+            echo "Route53 cname ce7-grp-2-app-'${{ github.ref_name }}'.sctp-sandbox.com created successfully." >> $GITHUB_STEP_SUMMARY
+          else
+            echo "Route53 cname creation failed." >> $GITHUB_STEP_SUMMARY
+          fi
+
+          # Check if DNS name lookup works
+          sleep 10
+          if [ "$(dig @8.8.8.8 +short ce7-grp-2-app-'${{ github.ref_name }}'.sctp-sandbox.com | grep amazonaws)" = "$EXTERNAL_IP" ]; then
+            echo "DNS name resolution successful."
+          else
+            echo "DNS name resolution failed."
+          fi
+
       - name: Create Route 53 CNAME Record
         if: ${{ github.ref_name == 'prod' }}
         run: |
@@ -453,3 +487,19 @@ jobs:
               }
             }]
           }'
+
+          # Check if CNAME record was created successfully
+          sleep 10
+          if [ "$(aws route53 list-resource-record-sets --hosted-zone-id $ZONE_ID --query "ResourceRecordSets[?Type == 'CNAME' && Name == 'ce7-grp-2-app.sctp-sandbox.com.'].ResourceRecords[*].Value" --output text)" = "$EXTERNAL_IP" ]; then
+            echo "route53 cname ce7-grp-2-app.sctp-sandbox.com created successfully." >> $GITHUB_STEP_SUMMARY
+          else
+            echo "route53 cname creation failed." >> $GITHUB_STEP_SUMMARY
+          fi
+
+          # Check if DNS name lookup works
+          sleep 10
+          if [ "$(dig @8.8.8.8 +short ce7-grp-2-app.sctp-sandbox.com | grep amazonaws)" = "$EXTERNAL_IP" ]; then
+            echo "DNS name resolution successful." >> $GITHUB_STEP_SUMMARY
+          else
+            echo "DNS name resolution failed." >> $GITHUB_STEP_SUMMARY
+          fi
